# Based on node server version 16
FROM node:16
# Working directory
WORKDIR '/app'
# Copy project dependencies into WORKDIR
COPY package.json .
# Install packages
RUN npm install
# Copy the rest of the code
COPY . .
# Build project for production
RUN npm run build
# Expose port
EXPOSE 3000
# Run server
CMD ["npm","run", "start"]