##################################################
# Not yet supported by Next.js with app directory
##################################################

FROM node:16-alpine AS builder

WORKDIR /app

COPY package.json ./

COPY package-lock.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx:1.22.1 AS server

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app /

EXPOSE 80