---
name: React Puppeteer Scenario
author: jannikr
version: 1

services:
  server:
    image: corporate-website-react_server
    ports:
      - 8080:80
    networks:
      - react-puppeteer-network
  client:
    # Use testing because stable version is not launching browser
    image: greencoding/puppeteer-chrome:testing
    setup-commands:
      - cp /tmp/repo/puppeteer-flow.js /var/www/puppeteer-flow.js
    networks:
      - react-puppeteer-network

flow:
  - name: Check Website
    container: client
    commands:
      - type: console
        command: node /var/www/puppeteer-flow.js
        note: Starting Puppeteer Flow
        parse-stdout-as-note: true

networks:
  react-puppeteer-network: