# Build on node version 16
FROM node:16
# Working directory
WORKDIR '/app'
# Copy project dependencies into WORKDIR
COPY package.json .
# Install packages
RUN npm install
# Copy the rest of the code
COPY . .
# Expose port
EXPOSE 3000
# Run application in dev-mode
CMD ["npm","run","dev"]