version: "3"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
# Since this file is only for building the server the client image can be skipped:
#  client:
#    image: greencoding/puppeteer-chrome
