# Build on node version 16
FROM node:16.14 AS build
# Working directory
WORKDIR /app
# Copy project dependencies into WORKDIR
COPY package*.json ./
# Install packages
RUN npm install
# Copy the rest of the code
COPY . .
# Build project for production
RUN npm run build -- --mode custom
# Based on nginx alpine server
FROM nginx:1.22.1 as server
# Copy nginx configuration
COPY ./nginx.conf /etc/nginx/nginx.conf
# Copy build files
COPY --from=build /app/dist /usr/share/nginx/html